# Selene config (v0.30+)
std = "roblox"

exclude = [
  "src/Shared/Types/*.luau", # type defs
]

[lints]
shadowing = "warn"
undefined_variable = "warn"
unused_variable = "warn"
roblox_incorrect_roact_usage = "allow"
