[package]
name = "azure/action-rpg-prototype"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit       = "sleitnick/knit@1.7.0"
Roact      = "jessekroeske/roact@1.4.2"
Rodux      = "jessekroeske/rodux@3.0.0"
Roact-Rodux = "neura-studios/roact-rodux@0.0.5"
Promise    = "evaera/promise@3.1.0"
Janitor    = "howmanysmall/janitor@1.13.13"
Signal = "sleitnick/signal@^1"
TableUtil = "sleitnick/table-util@^1"
Val        = "tumblewede/val@0.1.1"
ProfileStore = "vyon/profilestore@1.0.3"

